const CATEGORIES = {
 electronics:{icon:"⌁",label:"Electronics",examples:"phones, headphones, cords, game controllers",questions:[
  {id:"powers",text:"Does it power on?",options:[["yes","Yes"],["no","No"],["unknown","Not sure"]]},
  {id:"damage",text:"What is the main problem?",options:[["battery","Battery or charging"],["connection","Connection, sound, or software"],["physical","Cracked, bent, or physical damage"],["none","It works; I no longer need it"]]},
  {id:"battery",text:"Does it contain a battery?",options:[["yes","Yes"],["no","No"],["unknown","Not sure"]]}
 ]},
 clothing:{icon:"♧",label:"Clothing & shoes",examples:"shirts, jeans, jackets, shoes",questions:[
  {id:"clean",text:"Is it clean and odor-free?",options:[["yes","Yes"],["no","No"]]},
  {id:"wearable",text:"Is it still wearable?",options:[["yes","Yes"],["repair","Yes, with a small repair"],["no","No"]]},
  {id:"condition",text:"What is its condition?",options:[["good","Good condition"],["brand","Good condition / recognizable brand"],["damaged","Large stains, tears, or wear"]]}
 ]},
 furniture:{icon:"▣",label:"Furniture",examples:"chairs, tables, shelves, lamps",questions:[
  {id:"safe",text:"Is it structurally safe to use?",options:[["yes","Yes"],["repair","Needs a small repair"],["no","No"]]},
  {id:"damage",text:"Does it have water damage, mold, pests, or a strong odor?",options:[["none","No"],["minor","Minor cosmetic damage"],["major","Yes"]]},
  {id:"useful",text:"Would someone reasonably want it after cleaning or repair?",options:[["yes","Yes"],["no","No / not sure"]]}
 ]},
 appliance:{icon:"◉",label:"Small appliance",examples:"fans, blenders, toasters, lamps",questions:[
  {id:"powers",text:"Does it power on safely?",options:[["yes","Yes"],["no","No"],["unsafe","It sparks, smells burnt, or gets very hot"]]},
  {id:"issue",text:"What is the issue?",options:[["minor","Loose part, cord, switch, or simple blockage"],["motor","Motor or internal part"],["none","It works; I do not need it"]]},
  {id:"age",text:"How old is it approximately?",options:[["new","Under 5 years"],["old","5+ years"],["unknown","Not sure"]]}
 ]},
 sports:{icon:"◌",label:"Sports gear",examples:"bikes, rackets, balls, weights",questions:[
  {id:"safe",text:"Is it safe to use?",options:[["yes","Yes"],["repair","Needs a small repair"],["no","No"]]},
  {id:"damage",text:"What is the issue?",options:[["cosmetic","Cosmetic wear only"],["replaceable","Needs a grip, string, tire, or small part"],["structural","Cracked, bent, or structural damage"]]},
  {id:"useful",text:"Would someone else use it?",options:[["yes","Yes"],["no","No / not sure"]]}
 ]},
 packaging:{icon:"▤",label:"Packaging & materials",examples:"bottles, cans, boxes, containers",questions:[
  {id:"material",text:"What is it mostly made of?",options:[["paper","Paper or cardboard"],["glass","Glass"],["metal","Metal can or foil"],["plastic","Plastic"],["mixed","Mixed materials"]]},
  {id:"clean",text:"Is it empty, clean, and dry?",options:[["yes","Yes"],["no","No"]]},
  {id:"type",text:"Does it have food residue, a battery, chemicals, or sharp parts?",options:[["none","No"],["food","Food residue"],["hazard","Battery, chemical, or sharp part"]]}
 ]}
};
function inferCategory(text=""){const t=text.toLowerCase();if(/headphone|phone|tablet|electronic|charger|camera|keyboard|controller|speaker|cable/.test(t))return"electronics";if(/shirt|shoe|jean|clothing|jacket|dress/.test(t))return"clothing";if(/chair|table|desk|shelf|furniture|lamp/.test(t))return"furniture";if(/fan|blender|toaster|appliance|vacuum|coffee/.test(t))return"appliance";if(/bike|racket|ball|sport|weight/.test(t))return"sports";return null}
function getRecommendation(category,a){let primary="",reason="",alternatives=[];
 if(category==="electronics"){if(a.damage==="none"){primary="Donate or sell";reason="The item still works, so extending its life is better than discarding it.";alternatives=["Give it to a friend or community group","Recycle as e-waste only if no reuse option works"]}else if(a.powers==="yes"&&(a.damage==="battery"||a.damage==="connection")){primary="Repair first";reason="It powers on, which suggests the problem may be a battery, connection, setting, or replaceable component.";alternatives=["Sell or donate after repair","Use certified e-waste recycling if repair is not worthwhile"]}else{primary="Recycle as e-waste";reason="Electronics and batteries should not go in standard curbside recycling or household trash.";alternatives=["Check if a repair shop can diagnose it first","Remove personal data before recycling"]}}
 if(category==="clothing"){if(a.clean==="yes"&&a.wearable==="yes"){primary=a.condition==="brand"?"Sell or donate":"Donate or swap";reason="Clean, wearable clothing can keep serving someone instead of becoming textile waste.";alternatives=["Create a clothing swap","Keep as a backup or upcycle"]}else if(a.wearable==="repair"){primary="Repair or alter";reason="Small damage such as a missing button, loose seam, or broken zipper is often fixable.";alternatives=["Donate only after repair","Use textile recycling if it is no longer wearable"]}else{primary="Textile recycle or upcycle";reason="Damaged clothing is usually not suitable for donation, but may still have material value.";alternatives=["Cut into cleaning rags","Check a textile-recycling program"]}}
 if(category==="furniture"){if(a.damage==="major"||a.safe==="no"){primary="Special disposal or landfill";reason="Mold, pest damage, severe water damage, or unsafe structure can make furniture unsuitable for reuse.";alternatives=["Salvage safe hardware or wood only if appropriate","Check bulky-item disposal rules"]}else if(a.safe==="repair"||a.damage==="minor"){primary="Repair, then donate or sell";reason="Cosmetic damage and small structural repairs can often restore useful furniture.";alternatives=["Offer it free with full-condition notes","Upcycle or refinish it"]}else{primary="Donate, sell, or give away";reason="Safe, usable furniture has a high chance of being reused.";alternatives=["List it for free locally","Keep it in a community exchange"]}}
 if(category==="appliance"){if(a.powers==="unsafe"){primary="Stop using; recycle as e-waste";reason="Sparks, burning smells, or dangerous heat can signal an electrical hazard.";alternatives=["Do not place it in curbside recycling","Ask a qualified repairer before reuse"]}else if(a.issue==="none"){primary="Donate or sell";reason="A working appliance should be reused before it is recycled.";alternatives=["Give it to a neighbor or student","Keep as a backup"]}else if(a.powers==="yes"&&a.issue==="minor"){primary="Repair first";reason="A removable blockage, loose cord, switch, or replaceable part may be fixable.";alternatives=["Donate after repair","Recycle as e-waste if it cannot be safely repaired"]}else{primary="Repair assessment or e-waste recycle";reason="Internal motor problems can be harder to repair, but should not go in standard recycling.";alternatives=["Check manufacturer repair support","Use an electronics/appliance recycler"]}}
 if(category==="sports"){if(a.safe==="yes"&&a.useful==="yes"){primary="Donate, sell, or share";reason="Usable sports equipment can have a long second life.";alternatives=["Offer it to a youth program","Create a gear swap"]}else if(a.safe==="repair"||a.damage==="replaceable"){primary="Repair or replace the small part";reason="Grips, strings, tires, and similar parts are often less expensive than replacing the whole item.";alternatives=["Donate after repair","Sell as a repair project"]}else{primary="Reuse parts or dispose responsibly";reason="Cracked or structurally unsafe sports equipment should not be donated for use.";alternatives=["Salvage safe removable parts","Check material-specific recycling"]}}
 if(category==="packaging"){if(a.type==="hazard"){primary="Use special disposal";reason="Batteries, chemicals, and sharp items need a dedicated disposal method and should not enter standard recycling.";alternatives=["Keep it separate from household recycling","Check local hazardous-waste guidance"]}else if(a.material==="mixed"){primary="Reuse or landfill";reason="Mixed-material packaging is difficult to sort and is often not accepted curbside.";alternatives=["Separate materials if possible","Reuse for storage or crafts"]}else if(a.clean==="yes"&&a.type==="none"){primary="Recycle";reason="Clean, empty single-material packaging is more likely to be accepted in recycling systems.";alternatives=["Reuse it first if practical","Check your local accepted-material list"]}else{primary="Clean first, then check recycling";reason="Food residue can contaminate other recyclable material.";alternatives=["Reuse if cleaning is not practical","Dispose in trash if local rules reject it"]}}
 return {primary,reason,alternatives};}